import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FormBuilder, Validators, FormControl } from '@angular/forms';
import { Observable } from 'rxjs';
import { map, startWith } from 'rxjs/operators';
import { User } from '../../assets/services/user'
import { HashPasswordService } from '../../assets/services/hash-password.service'

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['../login/login.component.css', './register.component.css']
})

export class RegisterComponent implements OnInit {
  myControl = new FormControl();
  subbmitted : boolean = false;
  registerForm: any;
  login: string;
  password: string;
  city: any;
  filteredOptions: Observable<string[]>;
  newUser : User;

  constructor(private router: Router,
              private formBuilder: FormBuilder,
              private hash: HashPasswordService) { }

  get f () {return this.registerForm.controls;}

  ngOnInit() {
    if (localStorage.getItem("loggedUser")) {
      this.router.navigate(['/welcome']);
    }

    this.registerForm = this.formBuilder.group({
      formLogin: ['', Validators.required],
      formPassword: ['', [Validators.required, Validators.minLength(6)]],
      formCity: ['']     
    })

    this.filteredOptions = this.myControl.valueChanges
      .pipe(
        startWith(''),
        map(value => this._filter(value))
      );
  }

  private _filter(value: string): string[] {
    const filterValue = value.toLowerCase();

    return this.options.filter(option => option.toLowerCase().includes(filterValue));
  }

  onSubmit() {
    this.subbmitted = true;
    let newUser : User = {
      login: this.login,
      password: this.hash.hashPassword(this.password),
      city: this.city
    }

    let usersArray : User [] = [];

    if (!localStorage.getItem("usersArray")){
      usersArray.push(newUser);    
    } else {
      usersArray = JSON.parse(localStorage.getItem("usersArray"));
      usersArray.push(newUser);
    }

    localStorage.setItem("usersArray", JSON.stringify(usersArray));
    this.router.navigate(['/login']);
  }

  toLogin() {
    this.router.navigate(['/login']);
  }

   options : string [] = ["Bardo", "Bielawa",
            "Bierutów",
            "Bogatynia",
            "Boguszów-Gorce",
            "Boleslawiec",
            "Bolków",
            "Brzeg Dolny",
            "Bystrzyca Klodzka",
            "Chocianów",
            "Chojnów",
            "Duszniki Zdrój",
            "Dzierzoniów",
            "Glogów",
            "Gluszyca",
            "Góra",
            "Gryfów Slaski",
            "Jawor",
            "Jaworzyna Slaska",
            "Jedlina Zdrój",
            "Jelcz-Laskowice",
            "Jelenia Góra",
            "Kamienna Góra",
            "Karpacz",
            "Katy Wroclawskie",
            "Klodzko",
            "Kowary",
            "Kudowa Zdrój",
            "Ladek Zdrój",
            "Legnica",
            "Lesna",
            "Luban",
            "Lubawka",
            "Lubin",
            "Lubomierz",
            "Lwówek Slaski",
            "Mieroszów",
            "Miedzybórz",
            "Miedzylesie",
            "Milicz",
            "Mirsk",
            "Niemcza",
            "Nowa Ruda",
            "Nowogrodziec",
            "Oborniki Slaskie",
            "Olesnica",
            "Olawa",
            "Piechowice",
            "Piensk",
            "Pieszyce",
            "Pilawa Górna",
            "Polanica Zdrój",
            "Polkowice",
            "Prochowice",
            "Prusice",
            "Przemków",
            "Radków",
            "Siechnice",
            "Sobótka",
            "Stronie Slaskie",
            "Strzegom",
            "Strzelin",
            "Syców",
            "Szczawno Zdrój",
            "Szczytna",
            "Szklarska Poreba",
            "Scinawa",
            "Sroda Slaska",
            "Swidnica",
            "Swiebodzice",
            "Swieradów Zdrój",
            "Swierzawa",
            "Trzebnica",
            "Twardogóra",
            "Walbrzych",
            "Wasosz",
            "Wegliniec",
            "Wiazów",
            "Wlen",
            "Wojcieszów",
            "Wolów",
            "Wroclaw",
            "Zawidów",
            "Zabkowice Slaskie",
            "Zgorzelec",
            "Ziebice",
            "Zlotoryja",
            "Zloty Stok",
            "Zarów",
            "Zmigród",
            "Aleksandrów Kujawski",
            "Barcin",
            "Brodnica",
            "Brzesc Kujawski",
            "Bydgoszcz",
            "Chelmno",
            "Chelmza",
            "Chodecz",
            "Ciechocinek",
            "Dobrzyn nad Wisla",
            "Gniewkowo",
            "Golub-Dobrzyn",
            "Górzno",
            "Grudziadz",
            "Inowroclaw",
            "Izbica Kujawska",
            "Jablonowo Pomorskie",
            "Janikowo",
            "Janowiec Wielkopolski",
            "Kamien Krajenski",
            "Kcynia",
            "Koronowo",
            "Kowal",
            "Kowalewo Pomorskie",
            "Kruszwica",
            "Lipno",
            "Lubien Kujawski",
            "Lubraniec",
            "Labiszyn",
            "Lasin",
            "Mogilno",
            "Mrocza",
            "Naklo nad Notecia",
            "Nieszawa",
            "Nowe",
            "Pakosc",
            "Piotrków Kujawski",
            "Radziejów",
            "Radzyn Chelminski",
            "Rypin",
            "Sepólno Krajenskie",
            "Skepe",
            "Solec Kujawski",
            "Strzelno",
            "Szubin",
            "Swiecie",
            "Torun",
            "Tuchola",
            "Wabrzezno",
            "Wiecbork",
            "Wloclawek",
            "Znin",
            "Annopol",
            "Belzyce",
            "Biala Podlaska",
            "Bilgoraj",
            "Bychawa",
            "Chelm",
            "Deblin",
            "Frampol",
            "Hrubieszów",
            "Janów Lubelski",
            "Józefów",
            "Kazimierz Dolny",
            "Kock",
            "Krasnobród",
            "Krasnystaw",
            "Krasnik",
            "Lubartów",
            "Lublin",
            "Leczna",
            "Luków",
            "Miedzyrzec Podlaski",
            "Naleczów",
            "Opole Lubelskie",
            "Ostrów Lubelski",
            "Parczew",
            "Piaski",
            "Poniatowa",
            "Pulawy",
            "Radzyn Podlaski",
            "Rejowiec Fabryczny",
            "Ryki",
            "Stoczek Lukowski",
            "Szczebrzeszyn",
            "Swidnik",
            "Tarnogród",
            "Terespol",
            "Tomaszów Lubelski",
            "Wlodawa",
            "Zamosc",
            "Zwierzyniec",
            "Babimost",
            "Bytom Odrzanski",
            "Cybinka",
            "Czerwiensk",
            "Dobiegniew",
            "Drezdenko",
            "Gorzów Wielkopolski",
            "Gozdnica",
            "Gubin",
            "Ilowa",
            "Jasien",
            "Kargowa",
            "Kostrzyn",
            "Kozuchów",
            "Krosno Odrzanskie",
            "Lubniewice",
            "Lubsko",
            "Leknica",
            "Malomice",
            "Miedzyrzecz",
            "Nowa Sól",
            "Nowe Miasteczko",
            "Nowogród Bobrzanski",
            "Osno Lubuskie",
            "Rzepin",
            "Skwierzyna",
            "Slawa",
            "Slubice",
            "Strzelce Krajenskie",
            "Sulechów",
            "Sulecin",
            "Szlichtyngowa",
            "Szprotawa",
            "Swiebodzin",
            "Torzym",
            "Trzciel",
            "Witnica",
            "Wschowa",
            "Zbaszynek",
            "Zielona Góra",
            "Zagan",
            "Zary",
            "Aleksandrów Lódzki",
            "Belchatów",
            "Biala Rawska",
            "Blaszki",
            "Brzeziny",
            "Drzewica",
            "Dzialoszyn",
            "Glowno",
            "Kamiensk",
            "Koluszki",
            "Konstantynów Lódzki",
            "Krosniewice",
            "Kutno",
            "Lask",
            "Leczyca",
            "Lowicz",
            "Lódz",
            "Opoczno",
            "Ozorków",
            "Pabianice",
            "Pajeczno",
            "Piotrków Trybunalski",
            "Poddebice",
            "Przedbórz",
            "Radomsko",
            "Rawa Mazowiecka",
            "Sieradz",
            "Skierniewice",
            "Stryków",
            "Sulejów",
            "Szadek",
            "Tomaszów Mazowiecki",
            "Tuszyn",
            "Uniejów",
            "Warta",
            "Wielun",
            "Wieruszów",
            "Zdunska Wola",
            "Zelów",
            "Zgierz",
            "Zloczew",
            "Zychlin",
            "Alwernia",
            "Andrychów",
            "Biecz",
            "Bochnia",
            "Brzesko",
            "Brzeszcze",
            "Bukowno",
            "Chelmek",
            "Chrzanów",
            "Ciezkowice",
            "Czchów",
            "Dabrowa Tarnowska",
            "Dobczyce",
            "Gorlice",
            "Grybów",
            "Jordanów",
            "Kalwaria Zebrzydowska",
            "Kety",
            "Kraków",
            "Krynica",
            "Krzeszowice",
            "Libiaz",
            "Limanowa",
            "Maków Podhalanski",
            "Miechów",
            "Mszana Dolna",
            "Muszyna",
            "Myslenice",
            "Niepolomice",
            "Nowy Sacz",
            "Nowy Targ",
            "Nowy Wisnicz",
            "Olkusz",
            "Oswiecim",
            "Piwniczna Zdrój",
            "Proszowice",
            "Rabka",
            "Skala",
            "Skawina",
            "Slawków",
            "Slomniki",
            "Stary Sacz",
            "Sucha Beskidzka",
            "Sulkowice",
            "Szczawnica",
            "Swiatniki Górne",
            "Tarnów",
            "Trzebinia",
            "Tuchów",
            "Wadowice",
            "Wieliczka",
            "Wolbrom",
            "Zakopane",
            "Zator",
            "Zabno",
            "Bialobrzegi",
            "Biezun",
            "Blonie",
            "Brok",
            "Brwinów",
            "Chorzele",
            "Ciechanów",
            "Drobin",
            "Garwolin",
            "Gabin",
            "Glinojeck",
            "Gostynin",
            "Góra Kalwaria",
            "Grodzisk Mazowiecki",
            "Grójec",
            "Ilza",
            "Józefów",
            "Kaluszyn",
            "Karczew",
            "Kobylka",
            "Konstancin-Jeziorna",
            "Kosów Lacki",
            "Kozienice",
            "Legionowo",
            "Lipsko",
            "Laskarzew",
            "Lochów",
            "Lomianki",
            "Losice",
            "Maków Mazowiecki",
            "Marki",
            "Milanówek",
            "Minsk Mazowiecki",
            "Mlawa",
            "Mogielnica",
            "Mordy",
            "Mszczonów",
            "Myszyniec",
            "Nasielsk",
            "Nowe Miasto nad Pilica",
            "Nowy Dwór Mazowiecki",
            "Ostroleka",
            "Ostrów Mazowiecka",
            "Otwock",
            "Ozarów Mazowiecki",
            "Piaseczno",
            "Piastów",
            "Pilawa",
            "Pionki",
            "Plock",
            "Plonsk",
            "Podkowa Lesna",
            "Pruszków",
            "Przasnysz",
            "Przysucha",
            "Pultusk",
            "Raciaz",
            "Radom",
            "Radzymin",
            "Rózan",
            "Serock",
            "Siedlce",
            "Sierpc",
            "Skaryszew",
            "Sochaczew",
            "Sokolów Podlaski",
            "Sulejówek",
            "Szydlowiec",
            "Tluszcz",
            "Warka",
            "Warszawa",
            "Wesola",
            "Wegrów",
            "Wolomin",
            "Wyszków",
            "Wyszogród",
            "Wysmierzyce",
            "Zakroczym",
            "Zabki",
            "Zielonka",
            "Zwolen",
            "Zelechów",
            "Zuromin",
            "Zyrardów",
            "Baborów",
            "Biala",
            "Brzeg",
            "Byczyna",
            "Dobrodzien",
            "Glogówek",
            "Glubczyce",
            "Glucholazy",
            "Gogolin",
            "Gorzów Slaski",
            "Grodków",
            "Kedzierzyn-Kozle",
            "Kietrz",
            "Kluczbork",
            "Kolonowskie",
            "Korfantów",
            "Krapkowice",
            "Lesnica",
            "Lewin Brzeski",
            "Namyslów",
            "Niemodlin",
            "Nysa",
            "Olesno",
            "Opole",
            "Otmuchów",
            "Ozimek",
            "Paczków",
            "Praszka",
            "Prudnik",
            "Strzelce Opolskie",
            "Ujazd",
            "Wolczyn",
            "Zawadzkie",
            "Zdzieszowice",
            "Baranów Sandomierski",
            "Blazowa",
            "Brzozów",
            "Cieszanów",
            "Debica",
            "Dukla",
            "Dynów",
            "Glogów Malopolski",
            "Iwonicz Zdrój",
            "Jaroslaw",
            "Jaslo",
            "Jedlicze",
            "Kanczuga",
            "Kolbuszowa",
            "Krosno",
            "Lesko",
            "Lezajsk",
            "Lubaczów",
            "Lancut",
            "Mielec",
            "Narol",
            "Nisko",
            "Nowa Deba",
            "Nowa Sarzyna",
            "Oleszyce",
            "Pilzno",
            "Przemysl",
            "Przeworsk",
            "Radomysl Wielki",
            "Radymno",
            "Ropczyce",
            "Rudnik nad Sanem",
            "Rymanów",
            "Rzeszów",
            "Sanok",
            "Sedziszów Malopolski",
            "Sieniawa",
            "Sokolów Malopolski",
            "Stalowa Wola",
            "Strzyzów",
            "Tarnobrzeg",
            "Tyczyn",
            "Ulanów",
            "Ustrzyki Dolne",
            "Zagórz",
            "Augustów",
            "Bialystok",
            "Bielsk Podlaski",
            "Bransk",
            "Choroszcz",
            "Ciechanowiec",
            "Czarna Bialostocka",
            "Dabrowa Bialostocka",
            "Drohiczyn",
            "Goniadz",
            "Grajewo",
            "Hajnówka",
            "Jedwabne",
            "Kleszczele",
            "Knyszyn",
            "Kolno",
            "Lipsk",
            "Lapy",
            "Lomza",
            "Monki",
            "Nowogród",
            "Rajgród",
            "Sejny",
            "Siemiatycze",
            "Sokólka",
            "Stawiski",
            "Suchowola",
            "Suprasl",
            "Suraz",
            "Suwalki",
            "Szczuczyn",
            "Tykocin",
            "Wasilków",
            "Wysokie Mazowieckie",
            "Zabludów",
            "Zambrów",
            "Brusy",
            "Bytów",
            "Chojnice",
            "Czarna Woda",
            "Czarne",
            "Czersk",
            "Czluchów",
            "Debrzno",
            "Dzierzgon",
            "Gdansk",
            "Gdynia",
            "Gniew",
            "Hel",
            "Jastarnia",
            "Kartuzy",
            "Koscierzyna",
            "Krynica Morska",
            "Kwidzyn",
            "Lebork",
            "Leba",
            "Malbork",
            "Miastko",
            "Nowy Dwór Gdanski",
            "Nowy Staw",
            "Pelplin",
            "Prabuty",
            "Pruszcz Gdanski",
            "Puck",
            "Reda",
            "Rumia",
            "Skarszewy",
            "Skórcz",
            "Slupsk",
            "Sopot",
            "Starogard Gdanski",
            "Sztum",
            "Tczew",
            "Ustka",
            "Wejherowo",
            "Wladyslawowo",
            "Zukowo",
            "Bedzin",
            "Bielsko-Biala",
            "Bierun",
            "Blachownia",
            "Bytom",
            "Chorzów",
            "Cieszyn",
            "Czechowice-Dziedzice",
            "Czeladz",
            "Czerwionka-Leszczyny",
            "Czestochowa",
            "Dabrowa Górnicza",
            "Gliwice",
            "Imielin",
            "Jastrzebie Zdrój",
            "Jaworzno",
            "Kalety",
            "Katowice",
            "Klobuck",
            "Knurów",
            "Koniecpol",
            "Kozieglowy",
            "Krzepice",
            "Kuznia Raciborska",
            "Ledziny",
            "Lubliniec",
            "Laziska Górne",
            "Lazy",
            "Miasteczko Slaskie",
            "Mikolów",
            "Myslowice",
            "Myszków",
            "Ogrodzieniec",
            "Orzesze",
            "Piekary Slaskie",
            "Pilica",
            "Poreba",
            "Pszczyna",
            "Pszów",
            "Pyskowice",
            "Racibórz",
            "Radlin",
            "Radzionków",
            "Ruda Slaska",
            "Rybnik",
            "Rydultowy",
            "Siemianowice Slaskie",
            "Siewierz",
            "Skoczów",
            "Sosnowiec",
            "Sosnicowice",
            "Strumien",
            "Szczekociny",
            "Szczyrk",
            "Swietochlowice",
            "Tarnowskie Góry",
            "Toszek",
            "Tychy",
            "Ustron",
            "Wilamowice",
            "Wisla",
            "Wodzislaw Slaski",
            "Wojkowice",
            "Wozniki",
            "Zabrze",
            "Zawiercie",
            "Zarki",
            "Zory",
            "Zywiec",
            "Barlinek",
            "Barwice",
            "Bialogard",
            "Bialy Bór",
            "Bobolice",
            "Borne Sulinowo",
            "Cedynia",
            "Chociwel",
            "Chojna",
            "Choszczno",
            "Czaplinek",
            "Czlopa",
            "Darlowo",
            "Debno",
            "Dobra",
            "Dobrzany",
            "Drawno",
            "Drawsko Pomorskie",
            "Golczewo",
            "Goleniów",
            "Gryfice",
            "Gryfino",
            "Insko",
            "Kalisz Pomorski",
            "Kamien Pomorski",
            "Karlino",
            "Kepice",
            "Kolobrzeg",
            "Koszalin",
            "Lipiany",
            "Lobez",
            "Maszewo",
            "Mieszkowice",
            "Miedzyzdroje",
            "Miroslawiec",
            "Moryn",
            "Myslibórz",
            "Nowe Warpno",
            "Nowogard",
            "Pelczyce",
            "Ploty",
            "Polanów",
            "Police",
            "Polczyn Zdrój",
            "Pyrzyce",
            "Recz",
            "Resko",
            "Sianów",
            "Slawno",
            "Stargard Szczecinski",
            "Suchan",
            "Szczecin",
            "Szczecinek",
            "Swidwin",
            "Swinoujscie",
            "Trzcinsko Zdrój",
            "Trzebiatów",
            "Tuczno",
            "Walcz",
            "Wegorzyno",
            "Wolin",
            "Zlocieniec",
            "Bojanowo",
            "Borek Wielkopolski",
            "Buk",
            "Chodziez",
            "Czarnków",
            "Czempin",
            "Czerniejewo",
            "Dabie",
            "Dobra",
            "Dolsk",
            "Gniezno",
            "Golina",
            "Golancz",
            "Gostyn",
            "Grabów nad Prosna",
            "Grodzisk Wielkopolski",
            "Jarocin",
            "Jastrowie",
            "Jutrosin",
            "Kalisz",
            "Kepno",
            "Kleczew",
            "Klecko",
            "Klodawa",
            "Kobylin",
            "Kolo",
            "Konin",
            "Kostrzyn",
            "Koscian",
            "Kozmin Wielkopolski",
            "Kórnik",
            "Krajenka",
            "Krobia",
            "Krotoszyn",
            "Krzywin",
            "Krzyz Wielkopolski",
            "Ksiaz Wielkopolski",
            "Leszno",
            "Lubon",
            "Lwówek",
            "Lobzenica",
            "Margonin",
            "Miejska Górka",
            "Miedzychód",
            "Mikstat",
            "Miloslaw",
            "Mosina",
            "Murowana Goslina",
            "Nekla",
            "Nowe Skalmierzyce",
            "Nowy Tomysl",
            "Oborniki",
            "Obrzycko",
            "Odolanów",
            "Okonek",
            "Opalenica",
            "Osieczna",
            "Ostroróg",
            "Ostrów Wielkopolski",
            "Ostrzeszów",
            "Pila",
            "Pleszew",
            "Pniewy",
            "Pobiedziska",
            "Pogorzela",
            "Poniec",
            "Poznan",
            "Przedecz",
            "Puszczykowo",
            "Pyzdry",
            "Rakoniewice",
            "Raszków",
            "Rawicz",
            "Rogozno",
            "Rychwal",
            "Rydzyna",
            "Sieraków",
            "Skoki",
            "Slupca",
            "Sompolno",
            "Stawiszyn",
            "Steszew",
            "Sulmierzyce",
            "Swarzedz",
            "Szamocin",
            "Szamotuly",
            "Slesin",
            "Smigiel",
            "Srem",
            "Sroda Wielkopolska",
            "Trzcianka",
            "Trzemeszno",
            "Tuliszków",
            "Turek",
            "Ujscie",
            "Wagrowiec",
            "Wielen",
            "Wielichowo",
            "Witkowo",
            "Wolsztyn",
            "Wronki",
            "Wrzesnia",
            "Wyrzysk",
            "Wysoka",
            "Zagórów",
            "Zbaszyn",
            "Zduny",
            "Zlotów",
            "Zerków",
            "Barczewo",
            "Bartoszyce",
            "Biala Piska",
            "Biskupiec",
            "Bisztynek",
            "Braniewo",
            "Dobre Miasto",
            "Dzialdowo",
            "Elblag",
            "Elk",
            "Frombork",
            "Gizycko",
            "Goldap",
            "Górowo Ilaweckie",
            "Ilawa",
            "Jeziorany",
            "Ketrzyn",
            "Kisielice",
            "Korsze",
            "Lidzbark",
            "Lidzbark Warminski",
            "Lubawa",
            "Mikolajki",
            "Milakowo",
            "Milomlyn",
            "Mlynary",
            "Morag",
            "Mragowo",
            "Nidzica",
            "Nowe Miasto Lubawskie",
            "Olecko",
            "Olsztyn",
            "Olsztynek",
            "Orneta",
            "Orzysz",
            "Ostróda",
            "Paslek",
            "Pasym",
            "Pieniezno",
            "Pisz",
            "Reszel",
            "Ruciane-Nida",
            "Ryn",
            "Sepopol",
            "Susz",
            "Szczytno",
            "Tolkmicko",
            "Wegorzewo",
            "Zalewo",
            "Bodzentyn",
            "Busko Zdrój",
            "Checiny",
            "Chmielnik",
            "Cmielów",
            "Dzialoszyce",
            "Jedrzejów",
            "Kazimierza Wielka",
            "Kielce",
            "Konskie",
            "Kunów",
            "Malogoszcz",
            "Opatów",
            "Osiek",
            "Ostrowiec Swietokrzyski",
            "Ozarów",
            "Pinczów",
            "Polaniec",
            "Sandomierz",
            "Sedziszów",
            "Skalbmierz",
            "Skarzysko-Kamienna",
            "Starachowice",
            "Staszów",
            "Staporków",
            "Suchedniów",
            "Wachock",
            "Wloszczowa",
            "Zawichost"
    ]  
}
